#+TITLE: Signals
#+AUTHOR: Astar Bahouidi
#+DESCRIPTION: Chapter 10 from “Advanced Programming in the UNIX® Environment” Third Edition by W.  Richard Stevens and Stephen A.  Rago
#+STARTUP: showall

* Table Of Contents                                                   :toc_2:
- [[#101-introduction][10.1 Introduction]]
- [[#102-signal-concepts][10.2 Signal Concepts]]
- [[#103-signal-function][10.3 =signal= Function]]
- [[#104-unreliable-signals][10.4 Unreliable Signals]]
- [[#105-interrupted-system-calls][10.5 Interrupted System Calls]]
- [[#106-reentrant-functions][10.6 Reentrant Functions]]
- [[#107-sigcld-semantics][10.7 =SIGCLD= Semantics]]
- [[#108-reliable-signal-terminology-and-semantics][10.8 Reliable-Signal Terminology and Semantics]]
- [[#109-kill-and-raise-functions][10.9 =kill= and =raise= Functions]]
- [[#1010-alarm-and-pause-functions][10.10 =alarm= and =pause= Functions]]
- [[#1011-signal-sets][10.11 Signal Sets]]
- [[#1012-sigprocmask-function][10.12 =sigprocmask= Function]]
- [[#1013-sigpending-function][10.13 =sigpending= Function]]
- [[#1014-sigaction-function][10.14 =sigaction= Function]]
- [[#1015-sigsetjmp-and-siglongjmp-functions][10.15 =sigsetjmp= and =siglongjmp= Functions]]
- [[#1016-sigsuspend-function][10.16 =sigsuspend= Function]]
- [[#1017-abort-function][10.17 =abort= Function]]
- [[#1018-system-function][10.18 =system= Function]]
  - [[#example][Example]]
  - [[#example-1][Example]]
- [[#1019-sleep-nanosleep-and-clock_nanosleep-functions][10.19 =sleep=, =nanosleep=, and =clock_nanosleep= Functions]]
- [[#1020-sigqueue-function][10.20 =sigqueue= Function]]
- [[#1021-job-control-signals][10.21 Job-Control Signals]]
- [[#1022-signal-names-and-numbers][10.22 Signal Names and Numbers]]
- [[#1023-summary][10.23 Summary]]
- [[#exercises][Exercises]]
  - [[#exercise-101][Exercise 10.1]]
  - [[#exercise-102][Exercise 10.2]]
  - [[#exercise-103][Exercise 10.3]]
  - [[#exercise-104][Exercise 10.4]]
  - [[#exercise-105][Exercise 10.5]]
  - [[#exercise-106][Exercise 10.6]]
  - [[#exercise-107][Exercise 10.7]]
  - [[#exercise-108][Exercise 10.8]]
  - [[#exercise-109][Exercise 10.9]]
  - [[#exercise-1010][Exercise 10.10]]
  - [[#exercise-1011][Exercise 10.11]]
  - [[#exercise-1012][Exercise 10.12]]

* 10.1 Introduction
:PROPERTIES:
:CUSTOM_ID: section-10-1
:END:

* 10.2 Signal Concepts
:PROPERTIES:
:CUSTOM_ID: section-10-2
:END:

* 10.3 =signal= Function
:PROPERTIES:
:CUSTOM_ID: section-10-3
:END:

* 10.4 Unreliable Signals
:PROPERTIES:
:CUSTOM_ID: section-10-4
:END:

* 10.5 Interrupted System Calls
:PROPERTIES:
:CUSTOM_ID: section-10-5
:END:

* 10.6 Reentrant Functions
:PROPERTIES:
:CUSTOM_ID: section-10-6
:END:

* 10.7 =SIGCLD= Semantics
:PROPERTIES:
:CUSTOM_ID: section-10-7
:END:

* 10.8 Reliable-Signal Terminology and Semantics
:PROPERTIES:
:CUSTOM_ID: section-10-8
:END:

* 10.9 =kill= and =raise= Functions
:PROPERTIES:
:CUSTOM_ID: section-10-9
:END:

* 10.10 =alarm= and =pause= Functions
:PROPERTIES:
:CUSTOM_ID: section-10-10
:END:

* 10.11 Signal Sets
:PROPERTIES:
:CUSTOM_ID: section-10-11
:END:

* 10.12 =sigprocmask= Function
:PROPERTIES:
:CUSTOM_ID: section-10-12
:END:

* 10.13 =sigpending= Function
:PROPERTIES:
:CUSTOM_ID: section-10-13
:END:

* 10.14 =sigaction= Function
:PROPERTIES:
:CUSTOM_ID: section-10-14
:END:

* 10.15 =sigsetjmp= and =siglongjmp= Functions
:PROPERTIES:
:CUSTOM_ID: section-10-15
:END:

* 10.16 =sigsuspend= Function
:PROPERTIES:
:CUSTOM_ID: section-10-16
:END:

* 10.17 =abort= Function
:PROPERTIES:
:CUSTOM_ID: section-10-17
:END:

* 10.18 =system= Function
:PROPERTIES:
:CUSTOM_ID: section-10-18
:END:

In [[file:../proc/README.org::#section-8-13][Section 8.13]], we showed an implementation of the =system=
function. That version, however, did not do any signal
handling. *POSIX.1* requires that =system= ignore =SIGINT= and
=SIGQUIT= and block =SIGCHLD=. Before showing a version that handles
these signals correctly, let’s see why we need to worry about signal
handling.

** Example

The program shown in [[file:systest2.c][Figure 10.26]] (/systest2.c/) uses the version of
=system= from [[file:../proc/README.org::#section-8-13][Section 8.13]] ([[file:~/coding/c_prog/apue.3e/proc/system.c][Figure 8.22]]) to invoke the =ed(1)=
editor. (This editor has been part of *UNIX systems* for a long
time. We use it here because it is an interactive program that catches
the interrupt and quit signals. If we invoke =ed= from a shell and
type the interrupt character, it catches the interrupt signal and
prints a question mark. The =ed= program also sets the disposition of
the quit signal so that it is ignored.) The program in [[file:systest2.c][Figure 10.26]]
catches both =SIGINT= and =SIGCHLD=. If we invoke the program, we get

#+begin_src sh
$ ./systest2
a               # append text to the editor’s buffer
Here is one line of text
.               # period on a line by itself stops append mode
1,$p            # print first through last lines of buffer to see what’s there
Here is one line of text
w temp.foo      # write the buffer to a file
25              # editor says it wrote 25 bytes
q               # and leave the editor
caught SIGCHLD

#+end_src

When the editor terminates, the system sends the =SIGCHLD= signal to
the parent (the =systest2= process). We catch it and return from the
signal handler. But if it is catching the =SIGCHLD= signal, the parent
should be doing so because it has created its own children, so that it
knows when its children have terminated. The delivery of this signal
in the parent should be blocked while the system function is
executing. Indeed, this is what *POSIX.1* specifies. Otherwise, when
the child created by =system= terminates, it would fool the caller of
=system= into thinking that one of its own children terminated. The
caller would then use one of the =wait= functions to get the
termination status of the child, thereby preventing the =system=
function from being able to obtain the child’s termination status for
its return value.

If we run the program again, this time sending the editor an interrupt
signal, we get

#+begin_src sh
$ ./systest2
a               # append text to the editor’s buffer
hello, world
.               # period on a line by itself stops append mode
1,$p            # print first through last lines to see what’s there
hello, world
w temp.foo      # write the buffer to a file
13              # editor says it wrote 13 bytes
^C              # type the interrupt character
?               # editor catches signal, prints question mark
caught SIGINT   # and so does the parent process
q               # leave editor
caught SIGCHLD
#+end_src

Recall from [[file:../relation/README.org::#section-9-6][Section 9.6]] that typing the interrupt character causes the
interrupt signal to be sent to all the processes in the foreground
process group. [[#figure-10-27][Figure 10.27]] shows the arrangement of the processes
when the editor is running.

*** Figure 10.27
:PROPERTIES:
:CUSTOM_ID: figure-10-27
:END:

Foreground and background process groups for [[file:systest2.c][Figure 10.26]] (/systest2.c/).

#+begin_example
┏╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸┓     ┏╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸┓
╏┏━━━━━━━━━━━━━┓╏ fork╏┏━━━━━━━━━━━━━┓ fork ┏━━━━━━━━━━━━━┓ fork ┏━━━━━━━━━━━━┓╏
╏┃ login shell ┣──────▶┃ ./systest2  ┣─────▶┃ /bin/shell  ┣─────▶┃ /bin/ed    ┃╏
╏┗━━━━━━━━━━━━━┛╏ exec╏┗━━━━━━━━━━━━━┛ exec ┗━━━━━━━━━━━━━┛ exec ┗━━━━━━━━━━━━┛╏
┗╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸┛     ┗╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸╸┛
   background                              foreground
  process group                           process group

#+end_example

In this example, =SIGINT= is sent to all three foreground
processes. (The shell ignores it.) As we can see from the output, both
the =systest2= process and the editor catch the signal. But when we’re
running another program with the system function, we shouldn’t have
both the parent and the child catching the two terminal-generated
signals: interrupt and quit. Instead, these two signals should be sent
to the program that is running: the child. Since the command that is
executed by system can be an interactive command (as is the =ed=
program in this example) and since the caller of system gives up
control while the program executes, waiting for it to finish, the
caller of system should not be receiving these two terminal-generated
signals. For this reason, *POSIX.1* specifies that the system function
should ignore these two signals while waiting for the command to
complete.

** Example

[[file:system.c][Figure 10.28]] (/system.c/) Correct POSIX.1 implementation of system
function.

If we link the program in [[file:systest2.c][Figure 10.26]] (/systest2.c/) with this
implementation of the =system= function, the resulting binary differs
from the last (*flawed*) one in the following ways.

 1. No signal is sent to the calling process when we type the
    interrupt or quit character.

 2. When the =ed= command exits, =SIGCHLD= is not sent to the calling
    process. Instead, it is blocked until we unblock it in the last
    call to =sigprocmask=, after the system function retrieves the
    child’s termination status by calling =waitpid=.

  #+begin_quote
  *POSIX.1* states that if =wait= or =waitpid= returns the status of a
  child process while =SIGCHLD= is pending, then =SIGCHLD= should not
  be delivered to the process unless the status of another child
  process is also available. *FreeBSD 8.0*, *Mac OS X 10.6.8*, and
  *Solaris 10* all implement this semantic. *Linux 3.2.0*, however,
  doesn’t — =SIGCHLD= *remains pending after the* =system= *function
  calls* =waitpid=; *when the signal is unblocked*, *it is delivered
  to the caller*. If we called =wait= in the =sig_chld= function in
  [[file:systest2.c][Figure 10.26]], a *Linux system* would return =−1= with =errno= set to
  =ECHILD=, since the =system= function already retrieved the
  termination status of the child.
  #+end_quote

Many older texts show the ignoring of the interrupt and quit signals
as follows:

#+begin_src c
  if ((pid = fork()) < 0) {
    err_sys("fork error");
   } else if (pid == 0) {
    /* child */
    execl(...);
    _exit(127);
  }

  /* parent */
  old_intr = signal(SIGINT, SIG_IGN);
  old_quit = signal(SIGQUIT, SIG_IGN);
  waitpid(pid, &status, 0)
  signal(SIGINT, old_intr);
  signal(SIGQUIT, old_quit);
#+end_src

The problem with this sequence of code is that we have no guarantee
after the =fork= regarding whether the parent or child runs first. If
the child runs first and the parent doesn’t run for some time after,
an interrupt signal might be generated before the parent is able to
change its disposition to be ignored. For this reason, in [[file:system.c][Figure 10.28]]
(/system.c/), we change the disposition of the signals before the
=fork=.

Note that we have to reset the dispositions of these two signals in
the child before the call to =execl=. This allows =execl= to change
their dispositions to the default, based on the caller’s dispositions,
as we described in [[file:../proc/README.org::#section-8-10][Section 8.10]].

* 10.19 =sleep=, =nanosleep=, and =clock_nanosleep= Functions
:PROPERTIES:
:CUSTOM_ID: section-10-19
:END:

* 10.20 =sigqueue= Function
:PROPERTIES:
:CUSTOM_ID: section-10-20
:END:

* 10.21 Job-Control Signals
:PROPERTIES:
:CUSTOM_ID: section-10-21
:END:

* 10.22 Signal Names and Numbers
:PROPERTIES:
:CUSTOM_ID: section-10-22
:END:

* 10.23 Summary
:PROPERTIES:
:CUSTOM_ID: section-10-23
:END:

* Exercises
:PROPERTIES:
:CUSTOM_ID: exercises-10
:END:

** Exercise 10.1
:PROPERTIES:
:CUSTOM_ID: exercise-10-1
:END:

In Figure 10.2, remove the for (;;) statement. What happens and why?

** Exercise 10.2
:PROPERTIES:
:CUSTOM_ID: exercise-10-2
:END:

Implement the sig2str function described in Section 10.22.

** Exercise 10.3
:PROPERTIES:
:CUSTOM_ID: exercise-10-3
:END:

Draw pictures of the stack frames when we run the program from Figure 10.9.

** Exercise 10.4
:PROPERTIES:
:CUSTOM_ID: exercise-10-4
:END:

In Figure 10.11, we showed a technique that’s often used to set a timeout on an I/O
operation using setjmp and longjmp. The following code has also been seen:
signal(SIGALRM, sig_alrm);
alarm(60);
if (setjmp(env_alrm) != 0) {
/* handle timeout */
...
}
...
What else is wrong with this sequence of code?

** Exercise 10.5
:PROPERTIES:
:CUSTOM_ID: exercise-10-5
:END:

Using only a single timer (either alarm or the higher-precision setitimer), provide a set
of functions that allows a process to set any number of timers.

** Exercise 10.6
:PROPERTIES:
:CUSTOM_ID: exercise-10-6
:END:

Write the following program to test the parent–child synchronization functions in
Figure 10.24. The process creates a file and writes the integer 0 to the file. The process then
calls fork, and the parent and child alternate incrementing the counter in the file. Each
time the counter is incremented, print which process (parent or child) is doing the
increment.

** Exercise 10.7
:PROPERTIES:
:CUSTOM_ID: exercise-10-7
:END:

In the function shown in Figure 10.25, if the caller catches SIGABRT and returns from the
signal handler, why do we go to the trouble of resetting the disposition to its default and
call kill the second time, instead of simply calling _exit?

** Exercise 10.8
:PROPERTIES:
:CUSTOM_ID: exercise-10-8
:END:

Why do you think the siginfo structure (Section 10.14) includes the real user ID, instead
of the effective user ID, in the si_uid field?

** Exercise 10.9
:PROPERTIES:
:CUSTOM_ID: exercise-10-9
:END:

Rewrite the function in Figure 10.14 to handle all the signals from Figure 10.1. The
function should consist of a single loop that iterates once for every signal in the current
signal mask (not once for every possible signal).


** Exercise 10.10
:PROPERTIES:
:CUSTOM_ID: exercise-10-10
:END:

Write a program that calls sleep(60) in an infinite loop. Every five times through the
loop (every 5 minutes), fetch the current time of day and print the tm_sec field. Run the
program overnight and explain the results. How would a program such as the cron
daemon, which runs every minute on the minute, handle this situation?

** Exercise 10.11
:PROPERTIES:
:CUSTOM_ID: exercise-10-11
:END:

Modify Figure 3.5 as follows: (a) change BUFFSIZE to 100; (b) catch the SIGXFSZ signal
using the signal_intr function, printing a message when it’s caught, and returning
from the signal handler; and (c) print the return value from write if the requested number
of bytes wasn’t written. Modify the soft RLIMIT_FSIZE resource limit (Section 7.11) to
1,024 bytes and run your new program, copying a file that is larger than 1,024 bytes. (Try
to set the soft resource limit from your shell. If you can’t do this from your shell, call
setrlimit directly from the program.) Run this program on the different systems that
you have access to. What happens and why?

** Exercise 10.12
:PROPERTIES:
:CUSTOM_ID: exercise-10-12
:END:

Write a program that calls fwrite with a large buffer (about one gigabyte). Before calling
fwrite, call alarm to schedule a signal in 1 second. In your signal handler, print that the
signal was caught and return. Does the call to fwrite complete? What’s happening?
